### PR TITLE
make linter messages more detailed

### PR DESCRIPTION
**Pull request by torik42**
- always include the (long) message
- include the possible replacements
- include the context to see the output of YaLafi

- add the shortDescription of a replacement to the title of the solution

### CODE REVIEW

**Comment by mfbehrens99** [comment]
Thank you for all you contributions. I really appreciate that you help me to develop linter-yalafi.

Is it possible to remove the context. In my opinion this just makes the error message unnecessarily long and since YaLafi is replacing some parts of the text with other text It doesn't always match the real text. Moreover, the error is highlighted in the file which is anyway much better than the LT context string.
image

**Comment by torik42** [comment]
Thank you for starting the development! Before, I only used hunspell in the command line.

> Is it possible to remove the context. In my opinion this just makes the error message unnecessarily long and since YaLafi is replacing some parts of the text with other text It doesn't always match the real text. Moreover, the error is highlighted in the file which is anyway much better than the LT context string.

I came across a 'word repetition error' which was just because YaLafi replaced two equations with the same string. That’s why I find it helpful to see the Context because it is the YaLafi output. If you want, I can make it optional in the settings.

**Comment by mfbehrens99** [comment]
Okay I see. That is good reason for the context option. Did you report this to the original YaLafi project? I hope they can fix the issue there so in future this problem is not coming up again.

>If you want, I can make it optional in the settings.
I think it would be a good idea to create a new "group" (or however it is called) containing all the developer -ish settings. Then we can have one section for everybody and one section where everything can be customisable. What do you think about that?

**Comment by torik42** [comment]
I did not report it jet.

Should we maybe discuss the grouping of settings in a different issue? For now, I could either add an option to disable the context or just leave it there. I also don’t think it’s too annoying.

**Comment by mfbehrens99** [comment]
I agree. It's getting too long and right now we are starting to have parallel threads. It would be nice if you can add an option and we will discuss the order in another issue.

**Pull request merged**
