### PR TITLE
Sort Settings

### LINKED ISSUE #11: Sort options

### PR DESCRIPTION
**Pull request by mfbehrens99**
Fixes #11

### CODE REVIEW

**Comment by torik42** [comment]
This already looks great.

I would suggest having first the YaLafi Settings and second the LT settings. I guess most users need to set some YaLafi options, even if they use the online LT service. Also, if LT is properly configured, one does not need to change any LT settings.

Then I would put the `Show Context in Linter Message` just before the `Disable CRLF Warning`.

Can one provide an automatic preference conversion rule?

**Comment by mfbehrens99** [comment]
> I would suggest having first the YaLafi Settings and second the LT settings. I guess most users need to set some YaLafi options, even if they use the online LT service. Also, if LT is properly configured, one does not need to change any LT settings.

Okay, that makes sense. I swapped LT and YaLafi.


> Then I would put the `Show Context in Linter Message` just before the `Disable CRLF Warning`.

They are already in that order ...


> Can one provide an automatic preference conversion rule?

I'm sorry, but I don't get this question.

**Comment by torik42** [comment]
> > Then I would put the `Show Context in Linter Message` just before the `Disable CRLF Warning`.
> 
> They are already in that order ...

It has `order: 3` as had `yalafi` before. Hence, it showed up above `yalafi`. Now it is below `lt` because of alphabetical order. Nevertheless, one could just make it to `order: 4` to fix it at the right place. Also, I would order them also in the code, i.e. move `showContext…` and `disableCRLF…` below `yalafi`.

> > Can one provide an automatic preference conversion rule?
> 
> I'm sorry, but I don't get this question.

It’s my fault. I did not explain enough. When I install this changes, which rename the preferences, then I have to set them again. It would be nice, if for example the value from `ltserver` would be moved to `lt.server` when updating the package.

**Comment by mfbehrens99** [comment]
> > > Can one provide an automatic preference conversion rule?
> > 
> > 
> > I'm sorry, but I don't get this question.
> 
> It’s my fault. I did not explain enough. When I install this changes, which rename the preferences, then I have to set them again. It would be nice, if for example the value from `ltserver` would be moved to `lt.server` when updating the package.

Okay, now I understand the problem. Of course, we could write a script converting all settings to the new settings. However, I think that this is not worth the work, since only 24 people downloaded the package so far, and I am sure that not all of these people changed all settings of `linter-yalafi`. Nevertheless, if you want to write that script can create a branch based on this branch and later merge it into this branch.

**Comment by torik42** [comment]
I just thought this should often happen. If there is a method that atom calls at an update it would not be too difficult to implement. But I haven’t found such a thing. And I agree with 24 downloads in version 0.2.0 it’s okay to break settings. Although this would maybe cause some to use the LT online service against their will. See #22.

**Comment by mfbehrens99** [comment]
When if fix #23 this problem wouldn't even occur any more

**Comment by torik42** [comment]
#23 is exactly the problem I had, when thinking about grouping the preferences in #6 (see [this](https://github.com/mfbehrens99/linter-yalafi/pull/6#issuecomment-765950115) comment). If one only collapse the preferences that are less important, than the added structure is weird again.

I did not get YaLafi working without downloading LanguageTool and setting the path correctly. The YaLafi [installation guide](https://github.com/matze-dd/YaLafi#installation) also lists the installation of LanguageTool. If that is the case, also the LanguageTool path is important. Could you maybe verify that?

**Comment by torik42** [comment]
> I did not get YaLafi working without downloading LanguageTool and setting the path correctly. The YaLafi [installation guide](https://github.com/matze-dd/YaLafi#installation) also lists the installation of LanguageTool. If that is the case, also the LanguageTool path is important. Could you maybe verify that?

Okay, I tested again and it works. Then I like all your changes. Sorry for this.

**Comment by mfbehrens99** [comment]
Very good. Thank you for sharing your comments.

**Pull request merged**
